spring:
  profiles:
    active: dev #定义默认生效的环境
---
spring:
  profiles: dev
  jms:
    pub-sub-domain: false #配置消息服务类型 true 表示为topic消息 false 表示QUEUE消息
  activemq:
    user:  system #连接用户名
    password: root
    broker-url: tcp://activemq-server:61616 #消息组件的连接主机信息
server:
  port: 8090

---
spring:
  profiles: beta
server:
  port: 8080

---
spring:
  profiles: product
server:
  port: 80

#配置消息服务的组件